name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - .github/renovate.json
      - .github/workflows/renovate.yaml
concurrency:
  group: run-renovate-bot
  cancel-in-progress: true
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v39.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}